version: "3"
services:
  mongo:
    container_name: mongo-container
    image: mongo:3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    
  api: 
    container_name: api-container
    image: node:12
    working_dir: /www/b2wdigital
    restart: always
    command: bash -c "yarn --only=prod && yarn start"
    environment: 
      - MONGO_URL=mongodb://mongo:27017/b2wdigital
    volumes:
      - ./dist/:/www/b2wdigital/dist/
      - ./package.json:/www/b2wdigital/package.json
    ports:
      - "5050:5050"
    links:
      - mongo